### ISSUE TITLE
Example does not work 

### ISSUE THREAD

**Issue by nigel-dewar** [microsoftgraph/angular2-connect-rest-sample#7]
I have done everything right, and still getting this error

I have modified manifest to allow implicitFlow.

I have also added graph  to application in Azure AD config, and set ALL of the delegated file permissions available for files, I can authenticate, and am getting the token, but no files back. I checked my onedrive and there are files in it, but none being returned by http get call.

Have you guys tried running this example yourselves?

If I go to graph api explorer and use the http get call from this example I do get files, heaps of them which I have in my onedrive
https://graph.microsoft.io/en-us/graph-explorer#/

Cant understand what is happening then with this example. All I get back is from res in the console is
{"_body":"{\"@odata.context\":\"https://graph.microsoft.com/v1.0/$metadata#users('7b3f1e33-35b5-4918-ba9e-d3c15a89ab3e')/drive/root/children\",\"value\":[]}","status":200,"statusText":"Ok","headers":"[\n  [\n    \"application/json;odata.metadata=minimal;odata.streaming=true;IEEE754Compatible=false;charset=utf-8\"\n  ],\n  [\n    \"private\"\n  ],\n  [\n    \"ef27af17-5a93-41af-875b-e5f5c9af5246\"\n  ],\n  [\n    \"ef27af17-5a93-41af-875b-e5f5c9af5246\"\n  ]\n]","type":2,"url":"https://graph.microsoft.com/v1.0/me/drive/root/children"}

So nothing...., not sure why>?

**Comment by DianeD** [comment]
Hi @nigel-dewar . Thanks for reporting this issue. I get a list of files returned with the Files.Read permission only.
![image](https://cloud.githubusercontent.com/assets/8431452/20294926/87877a1e-aab6-11e6-8d0a-f522b2bf8e72.png)
My user consents to the Files.Read (and User.Read from AAD) permissions during log in, and I see "scp": "Files.Read User.Read" when I decode the token in jwt.io. Is this also the case for you?

**Comment by nigel-dewar** [comment]
Yes it is definitely selected
![image](https://cloud.githubusercontent.com/assets/9402456/20335746/dc9d55f4-ac10-11e6-9aff-66243389a518.png)

**Comment by nigel-dewar** [comment]
![image](https://cloud.githubusercontent.com/assets/9402456/20335760/014fdb56-ac11-11e6-893e-170ec4266ff4.png)

**Comment by DianeD** [comment]
Thanks @nigel-dewar . Sorry, but I meant "Can you please paste your access token into a decoder (like http://jwt.io/)?". Then you can inspect the token--it MAY CONTAIN PRIVATE DATA so don't paste it here. There should be a "scp" section that shows all the permissions that are included in the token. That "scp" should include "Files.Read User.Read".

**Comment by DianeD** [comment]
Hi @nigel-dewar . If this still reproduces for you, please reopen this issue.
