### ISSUE TITLE
It does not work!

### ISSUE THREAD

**Issue by vincent-chan-hk** [microsoftgraph/angular2-connect-rest-sample#8]

**Comment by DianeD** [comment]
Hi @vincent-chan-hk . Thanks for reporting this issue. Are you able to log in as a user from the tenant where the app is registered?

**Comment by vincent-chan-hk** [comment]
I cannot. It seems that Microsoft updated a new standard and your code did
not keep it updated.

2017年1月4日 07:30 於 "DianeD" <notifications@github.com> 寫道：

**Comment by DianeD** [comment]
What behavior are you seeing? Are you prompted to consent? Do you get an error on the page or in the address bar? 

I was able to log in and run the sample with a few users from my tenant. For one of the users, I did have to click the Connect button twice before the sample loaded correctly.

**Comment by vincent-chan-hk** [comment]
No consent! I click without any response in my Chrome. Anyway, if you can
log in successfully, your code should be fine but you are using ADSL.js.
How you rate between your method and Kurve.js? Thanks!

**Comment by DianeD** [comment]
Hi Vincent. I haven't tried Kurve.js. In general, we try to stick with [supported or compatible libraries](https://docs.microsoft.com/en-us/azure/active-directory/active-directory-v2-libraries) for the samples. 

You might try asking about it on [stackoverflow](https://stackoverflow.com/questions/tagged/microsoftgraph) (tagged with [microsoftgraph]).

**Comment by vincent-chan-hk** [comment]
Hi Diane,
Thank you very much! Happy New Year! :)
Vincent

**Comment by DianeD** [comment]
Thanks Vincent :)
